#!/usr/bin/env python3

# Print the path to a random image in $HOME/dotfiles/Wallpapers

import os
import random

wallpapers_dir = os.path.expanduser("~/dotfiles/Wallpapers")

wallpapers = os.listdir(wallpapers_dir)
wallpaper = random.choice(wallpapers)

print(os.path.join(wallpapers_dir, wallpaper))
