# SPDX-FileCopyrightText: Elfi Ox <https://github.com/elfi-ox> 
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["*.jpg", "*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Elfi Ox <https://github.com/elfi-ox>"
SPDX-License-Identifier = "CC0-1.0"
