return {
	require("spandan.plugins.mini"),
	require("spandan.plugins.colorschemes"),
	require("spandan.plugins.nvimtree"),
	require("spandan.plugins.nvim-cmp"),
	--require("spandan.plugins.codeium"),
	require("spandan.plugins.copilot"),
	--require('spandan.plugins.customlsp'),
	require("spandan.plugins.lspaddons"),
	require("spandan.plugins.dap"),
	require("spandan.plugins.fidget"),
	require("spandan.plugins.git"),
	-- require('spandan.plugins.lspconfig'),
	require("spandan.plugins.noice"),
	require("spandan.plugins.telescope"),
	require("spandan.plugins.treesitter"),
	require("spandan.plugins.visual"),
	require("spandan.plugins.whichkey"),
	require("spandan.plugins.oil"),
	require("spandan.plugins.mpv"),
	require("spandan.plugins.render-md"),
	require("spandan.plugins.games"),
	require("spandan.plugins.project-manager"),
	require("spandan.plugins.qol"),
	-- 	require('spandan.plugins.hardtime'),
	require("spandan.plugins.zotcite"),
	--require("spandan.plugins.ollama-copilot"),
	require("spandan.plugins.parinfer"),
}
