[FileDialog]
history=file:///run/media/spandan, file:///home/spandan/Downloads, file:///run/media/spandan/Data/Books Sorted/PDF/Medical books/1st Prof/Anatomy/Gray's anatomy for students, file:///run/media/spandan/Data/Books Sorted/PDF/Medical books/Prepladder Notes, file:///run/media/spandan/Data/Books Sorted/PDF/Medical books/Marrow Notes, file:///run/media/spandan/Data/Books Sorted/PDF/Coding
lastVisited=file:///run/media/spandan/Data/Books Sorted/PDF/Coding
qtVersion=5.15.5
shortcuts=file:, file:///home/spandan
sidebarWidth=113
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x91\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x92\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1R\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0\x93\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=List
